---
- name: Install Android Studio
  hosts: localhost
  connection: local
  tasks:

  - name: Enable ability to check for existing packages
    package_facts:
      manager: "auto"

  - name: Install Snap
    shell: sudo apt install -y snapd
    when: "'snap' not in ansible_facts.packages"

  - name: Install Flutter
    shell: sudo snap install flutter --classic
    when: "'flutter' not in ansible_facts.packages"

  - name: Install Chrome/Chromium
    shell: sudo snap install chromium
    when: "'chromium' not in ansible_facts.packages"


