---
- name: Install Android Studio
  hosts: localhost
  connection: local
  tasks:

  - name: Check if Snap installed
    package_facts:
      manager: "auto"

  - name: Install Snap
    shell: sudo apt install -y snapd
    when: "'snap' not in ansible_facts.packages"

  - name: Install Android Studio
    shell: sudo snap install android-studio --classic
    when: "'snap' not in ansible_facts.packages"
